name: scid
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  # Core conda packages
  - python=3.13
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python_abi=3.13
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  # Pip packages
  - pip:
    - accelerate==0.27.2
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - contourpy==1.3.1
    - cycler==0.12.1
    - diffusers==0.26.3
    - filelock==3.17.0
    - fonttools==4.56.0
    - fsspec==2025.2.0
    - huggingface-hub==0.25.2
    - idna==3.10
    - importlib-metadata==8.6.1
    - jinja2==3.1.5
    - kiwisolver==1.4.8
    - markupsafe==3.0.2
    - matplotlib==3.10.1
    - mpmath==1.3.0
    - networkx==3.4.2
    - numpy==2.2.3
    - packaging==24.2
    - pillow==11.1.0
    - psutil==7.0.0
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - pyvdirs==1.0.0
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - safetensors==0.5.3
    - six==1.17.0
    - sympy==1.13.1
    - torch==2.6.0
    - torchaudio==2.6.0
    - torchvision==0.21.0
    - tqdm==4.67.1
    - triton==3.2.0
    - typing-extensions==4.12.2
    - urllib3==2.3.0
    - zipp==3.21.0
    # CUDA related packages
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127 