# Run for different batch size
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 512 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_0512" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_0512.txt"
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 1024 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_1024" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_1024.txt"
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 2048 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_2048" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_2048.txt"
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 8192 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_8192" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_8192.txt"

# Run for different batch size, but adjusting also the total number of iterations to see the same amount of data points
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 512 --total-iter 32768 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_0512_Adjusted" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_0512_Adjusted.txt"
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 1024 --total-iter 16384 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_1024_Adjusted" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_1024_Adjusted.txt"
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 2048 --total-iter 8192 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_2048_Adjusted" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_2048_Adjusted.txt"
python ToyExample/toy_example.py train --guidance --guide-path "ToyExample/00_PreTrained/Ref/iter0512.pkl" --batch-size 8192 --total-iter 2048 --invert --acid --outdir "ToyExample/24_BatchSize/ACID_size_8192_Adjusted" --seed 0 --val --test --verbose --logging "ToyExample/24_BatchSize/log_ACID_size_8192_Adjusted.txt"